const PLANS={
  free:{id:"free",label:"Free",price:"R$ 0",period:"sempre grátis",color:"#888880",badge:"GRÁTIS",
    headline:"Comece sem pagar nada",
    features:[
      {t:"1 profissional",ok:true},
      {t:"Agendamento ilimitado",ok:true},
      {t:"2% de comissão por agendamento",ok:true,note:"deduzido automaticamente"},
      {t:"Gestão financeira",ok:false},
      {t:"Múltiplos profissionais",ok:false},
      {t:"Fidelização de clientes",ok:false},
      {t:"Controle de estoque",ok:false},
      {t:"Social Mavi IA",ok:false},
      {t:"Isenção da taxa de 2%",ok:false},
    ],
    allowed:["agenda"],cta:"Usar Grátis"},
  mv:{id:"mv",label:"Plano MV",price:"R$ 59,99",period:"/mês",color:Y,badge:"POPULAR",
    headline:"Para empresas em crescimento",
    features:[
      {t:"3 profissionais",ok:true},
      {t:"Agendamento ilimitado",ok:true},
      {t:"Isenção da taxa de 2%",ok:true},
      {t:"Gestão financeira",ok:true},
      {t:"Dashboard por profissional",ok:true},
      {t:"Relatório de despesas",ok:true},
      {t:"Social Mavi IA",ok:false},
      {t:"Sistema de fidelização",ok:false},
      {t:"Controle de estoque",ok:false},
    ],
    allowed:["agenda","financeiro"],cta:"Assinar MV"},
  diamante:{id:"diamante",label:"Diamante",price:"R$ 89,99",period:"/mês",color:"#B9F2FF",badge:"COMPLETO",
    headline:"O poder total da sua empresa",
    features:[
      {t:"✨ Tudo do Plano MV",ok:true,hl:true},
      {t:"✨ Social Mavi IA",ok:true,hl:true,note:"especialista em social mídia"},
      {t:"✨ Sistema de Fidelização",ok:true,hl:true,note:"pontos + WhatsApp automático"},
      {t:"Controle de estoque",ok:true},
      {t:"Gestão financeira detalhada",ok:true,note:"gráficos e relatórios completos"},
      {t:"Integrações premium",ok:true,note:"WhatsApp, Google, Mercado Pago, PagSeguro, Pix e link de pagamento"},
      {t:"Profissionais ilimitados",ok:true},
      {t:"Isenção da taxa de 2%",ok:true},
    ],
    allowed:["agenda","financeiro","ia","fidelizacao"],cta:"Assinar Diamante"},
};
